[workspace]
members = ["netsim", "netsim-async", "netsim-core", "netsim-ffi"]
resolver = "2"


[profile.release]
lto = true
panic = "abort"

[profile.release.package.netsim-ffi]
opt-level = 3
strip = true
