on:
  push:
    branches: [main]
  pull_request:

name: Tests C Bindings

jobs:
  build:
    name: Tests C Bindings
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Run cargo build
        run: cargo build --package netsim-ffi

      - name: Run Make
        working-directory: netsim-ffi/c_tests
        run: make

      - name: Run netsim C tests
        working-directory: netsim-ffi/c_tests
        env:
          LD_LIBRARY_PATH: ../../target/debug/:$LD_LIBRARY_PATH
        run: ./netsim
