on:
  push:
    branches: [main]
  pull_request:

name: Tests

jobs:
  build:
    name: Tests
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo test
        run: cargo test --workspace --all

      - name: Run Netsim Example
        run: cargo run --example simple

      - name: Run Netsim Async Example
        run: cargo run --example simple_async